### PR TITLE
Save 37 bytes in fizzbuzz.rb

### PR DESCRIPTION
**Pull request by fnimick**

### CODE REVIEW

**Review by doctaphred — CHANGES_REQUESTED** [review]
Too many lines, readers might get confused

**Comment by fnimick** [comment]
The newline is important because it pads the string out to the correct length for the magical string slicing to work. `puts` will ignore the newline, so the output is correct according to the spec.

If we could output `Buzz ` and `FizzBuzz ` with the trailing space for multiples of 5 and 15, respectively, then we could replace the newline with a trailing space.

**Comment by llllllllll** [comment]
> If we could output Buzz and FizzBuzz with the trailing space for multiples of 5 and 15, respectively, then we could replace the newline with a trailing space.

This is an interesting question; do people think that the visual output is all that matters or the actual text?

**Comment by doctaphred** [comment]
Trailing whitespace wastes trees, and can be used to send subliminal messages.

If you invest one extra byte to change

```ruby
'FizzBuzz
'
```

to

```ruby
"FizzBuzz\n"
```

you can significantly increase code clarity while still saving saving the planet.

**Comment by llllllllll** [comment]
> invest one extra byte

How do you ban someone from commenting in a repo?

**Comment by llllllllll** [comment]
this will save us a lot of disk space on our production servers, thanks!

**Comment by TylerAldrich** [comment]
I feel like i just watched history in the making here. I can't wait to tell my children about the day @fnimick saved not just 37 bytes, but the world.

**Pull request merged**
